name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python files
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          black --check .

      - name: Setup PowerShell
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Validate PowerShell script
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path "vmware-cis-run-checks.ps1" -Severity @('Error')
          if ($results) {
            Write-Host "PowerShell errors found:"
            $results | Format-Table
            exit 1
          }
          Write-Host "PowerShell validation passed"

      - name: Validate JSON files
        run: |
          find . -name "*.json" -exec python -m json.tool {} \; > /dev/null

      - name: Validate YAML files
        run: |
          python -c "import yaml; import sys; [yaml.safe_load(open(f)) for f in sys.argv[1:]]" .github/workflows/*.yml

      - name: Check file permissions
        run: |
          find . -type f -name "*.ps1" -exec chmod +x {} \;
          echo "File permissions validated"

      - name: Repository structure validation
        run: |
          echo "Validating repository structure..."
          test -f README.md || (echo "README.md missing" && exit 1)
          test -f LICENSE || (echo "LICENSE missing" && exit 1)
          test -f vmware-cis-run-checks.ps1 || (echo "Main script missing" && exit 1)
          echo "Repository structure validation passed"