name: Publish to PowerShell Gallery

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  security-events: write
  actions: read

  release:
    types: [published]
  workflow_dispatch:

